### ISSUE TITLE
🌈 显示优化 | 登录页点击验证码色差

### ISSUE THREAD

**Issue by hu-qi** [d2-projects/d2-admin-renren-security-enterprise#5]
## 原因
验证码采用backgroundImage渲染，当刷新时，会先显示默认的background-color，和图片有色差，产生类似**闪动**的效果。
如图，比较直观：
![backgroundImage](https://user-images.githubusercontent.com/17986122/56945402-a837c780-6b59-11e9-8295-f30f4dc93a24.gif)
## 建议
修改默认background-color，值接近验证码背景
```css
.login-captcha {
      background-color: #dfdfdf;
      //  ...
    }
```
修改后效果，如图：
![backgroundImage](https://user-images.githubusercontent.com/17986122/56945610-504d9080-6b5a-11e9-9481-52f79c5b27a4.gif)

感谢大佬开源，学习中...
